### ISSUE TITLE
爆発範囲設定した時に、大量に爆弾置くと固まる

### ISSUE THREAD

**Issue by lirlia** [recursion-team-v/bomb#162]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/10017674/211177768-b72cb72a-c4bc-4707-b999-46403b672a4e.png">

**Comment by lirlia** [comment]
```
phaser.js:215085 Uncaught TypeError: Cannot read properties of undefined (reading 'sys')
    at new MatterPhysics2 (phaser.js:215085:30)
    at getDimensionalMap (Map.ts:12:14)
    at Bomb.calcBlastRange (Bomb.ts:134:17)
    at Bomb.explode (Bomb.ts:124:21)
    at Function.callback (Bomb.ts:206:11)
    at Clock2.update (phaser.js:210738:36)
    at EventEmitter2.emit (phaser.js:1928:33)
    at Systems2.step (phaser.js:49066:16)
    at SceneManager2.update (phaser.js:100289:21)
    at Game2.step (phaser.js:162805:20)
```

**Comment by lirlia** [comment]
ここにログポイントを仕込んだら空のシーンが渡されてることがわかった。

<img width="738" alt="image" src="https://user-images.githubusercontent.com/10017674/211178009-4e2f4fa7-c10a-4155-82fd-bc69099be162.png">


```ts
  private calcBlastRange(): Map<Constants.DIRECTION_TYPE, number> {
    const map = getDimensionalMap(
      // TODO: サーバから受け取ったマップの X/ Y のタイル数を使う
      Constants.TILE_ROWS,
      Constants.TILE_COLS,
      this.scene,
      getHighestPriorityFromBodies
    );
```

ここで爆弾の持ってるシーンを渡してるのだが、爆弾が消えると参照できなくなるのでエラーになってるのかな。
ということで Phaser から直接 scene を引っ張って渡してみる

**Comment by lirlia** [comment]
ここにログポイントを仕込んだら空のシーンが渡されてることがわかった。

<img width="738" alt="image" src="https://user-images.githubusercontent.com/10017674/211178009-4e2f4fa7-c10a-4155-82fd-bc69099be162.png">


```ts
  private calcBlastRange(): Map<Constants.DIRECTION_TYPE, number> {
    const map = getDimensionalMap(
      // TODO: サーバから受け取ったマップの X/ Y のタイル数を使う
      Constants.TILE_ROWS,
      Constants.TILE_COLS,
      this.scene,
      getHighestPriorityFromBodies
    );
```

ここで爆弾の持ってるシーンを渡してるのだが、爆弾が消えると参照できなくなるのでエラーになってるのかな。
ということで Phaser から直接 scene を引っ張って渡してみる

**Comment by lirlia** [comment]
window.game に突っ込まれてたのでそれ使ったらいい感じに取得できるようになったが、
今度はこっち。

```
phaser.js:214486 Uncaught TypeError: Cannot read properties of undefined (reading 'position')
    at Bomb.get [as x] (phaser.js:214486:30)
    at Bomb.calcBlastRange (Bomb.ts:149:21)
    at Bomb.explode (Bomb.ts:127:21)
    at Function.callback (Bomb.ts:209:11)
    at Clock2.update (phaser.js:210738:36)
    at EventEmitter2.emit (phaser.js:1928:33)
    at Systems2.step (phaser.js:49066:16)
    at SceneManager2.update (phaser.js:100289:21)
    at Game2.step (phaser.js:162805:20)
    at TimeStep2.step (phaser.js:89366:14)
```

**Comment by lirlia** [comment]
```ts
    // 現在のユーザの爆弾の位置を取得
    const x = (this.x - Constants.TILE_WIDTH / 2) / Constants.TILE_WIDTH;
    const y =
      (this.y - Constants.TILE_HEIGHT / 2 - Constants.HEADER_HEIGHT) / Constants.TILE_HEIGHT;

    // 現在のユーザの爆弾の位置から上下左右の範囲を計算
    const m = new Map<Constants.DIRECTION_TYPE, number>();
```

**Comment by lirlia** [comment]
```ts
    // 現在のユーザの爆弾の位置を取得
    const x = (this.stableX - Constants.TILE_WIDTH / 2) / Constants.TILE_WIDTH;
    const y =
      (this.stableY - Constants.TILE_HEIGHT / 2 - Constants.HEADER_HEIGHT) / Constants.TILE_HEIGHT;
```

に変える

**Comment by lirlia** [comment]
落ち無くなったけど、たくさんボムを誘爆すると処理落ちする


https://user-images.githubusercontent.com/10017674/211178444-d6dbd73c-d699-4f49-8d8b-604eca20cab7.mov

**Comment by lirlia** [comment]
同じマスにいくつも rectangle を描画するのが辛いのかもしれない

**Comment by lirlia** [comment]
一旦問題になったら再考する

**Comment by lirlia** [comment]
なんか治ってた
